### PR TITLE
Feat: adding in Build homepage

### PR DESCRIPTION
**Pull request by stephanwampouille**
This PR adds a homepage screen for users that are already registered and assumed to have completed the basic training screen that shows for anon users.

### CODE REVIEW

**Comment by stephanwampouille** [comment]
Screen Shot 2023-01-11 at 4 13 39 PM

**Comment by stephanwampouille** [comment]
Screen Shot 2023-01-11 at 4 14 27 PM

**Comment by stephanwampouille** [comment]
While adding the compatibly for export Credentials I opted to just import the func twice, one in the main header so that It would be loaded for use of the emitter and the second in the Options component. So a few thoughts on this. I could use the emitter.emit again in options to reduce the second import or another thought I could also add an emitter event for import so that we do not have to make another call to the config at all and just use emitter.emit in the Options component

**Comment by stephanwampouille** [comment]
ready for review @kenrick

**Review by kenrick — APPROVED** [review]
Looks good

**Pull request merged**
