### PR TITLE
Rip out terminal entirely

### PR DESCRIPTION
**Pull request by khyberspache**

### CODE REVIEW

**Review by privateducky — CHANGES_REQUESTED** [review]
I think you went 1 step too far on this one, and removed the bottom pane (which shows the tests/VSTs in the pop-up sidebar). that pane may be dynamic though and my lack of updated JS SDK may be hiding it... thoughts?

**Comment by khyberspache** [comment]
> I think you went 1 step too far on this one, and removed the bottom pane (which shows the tests/VSTs in the pop-up sidebar). that pane may be dynamic though and my lack of updated JS SDK may be hiding it... thoughts?

CleanShot 2023-01-02 at 19 22 11@2x
The pop-up sidebars are still there I believe. Could you elaborate on what you're referring to in this context?

**Comment by khyberspache** [comment]
They don't populate right now because I have to update the backend API calls.  I'll add that to this PR

**Comment by privateducky** [comment]
> They don't populate right now because I have to update the backend API calls.  I'll add that to this PR

That's what I figured, great!

**Review by privateducky — APPROVED** [review]
Let it rip

**Pull request merged**
